// src/lib/data.ts
import type { Item } from './types';
import { placeholderImages } from './placeholder-images.json';

export const items: Item[] = [
  {
    id: '1',
    name: 'iPhone 13 Pro',
    status: 'Lost',
    category: 'Electronics',
    description: 'Lost my iPhone 13 Pro with a black case. The lock screen has a picture of a golden retriever.',
    date: '2024-07-20T09:00:00.000Z',
    location: 'Library',
    imageUrl: placeholderImages.find(img => img.id === 'lost-phone')?.imageUrl || '',
    imageHint: placeholderImages.find(img => img.id === 'lost-phone')?.imageHint || '',
    user: { name: 'Alice', avatarUrl: 'https://picsum.photos/seed/user1/40/40' },
  },
  {
    id: '2',
    name: 'Set of Keys',
    status: 'Found',
    category: 'Accessories',
    description: 'Found a set of keys on a blue lanyard near the cafeteria entrance. Has a small keychain that looks like a cat.',
    date: '2024-07-21T14:30:00.000Z',
    location: 'Cafeteria',
    imageUrl: placeholderImages.find(img => img.id === 'found-keys')?.imageUrl || '',
    imageHint: placeholderImages.find(img => img.id === 'found-keys')?.imageHint || '',
    user: { name: 'Bob', avatarUrl: 'https://picsum.photos/seed/user2/40/40' },
  },
  {
    id: '3',
    name: 'Spiral Notebook',
    status: 'Lost',
    category: 'Books',
    description: 'Lost a blue spiral notebook with "Organic Chemistry" written on the front. Has a lot of important notes inside.',
    date: '2024-07-19T11:00:00.000Z',
    location: 'Classroom',
    imageUrl: placeholderImages.find(img => img.id === 'lost-notebook')?.imageUrl || '',
    imageHint: placeholderImages.find(img => img.id === 'lost-notebook')?.imageHint || '',
    user: { name: 'Charlie', avatarUrl: 'https://picsum.photos/seed/user3/40/40' },
  },
  {
    id: '4',
    name: 'Student ID Card',
    status: 'Found',
    category: 'ID Cards',
    description: 'Found a student ID card for a student named "Diana Prince". Handed it to the front desk at the sports complex.',
    date: '2024-07-22T18:00:00.000Z',
    location: 'Sports Complex',
    imageUrl: placeholderImages.find(img => img.id === 'found-id')?.imageUrl || '',
    imageHint: placeholderImages.find(img => img.id === 'found-id')?.imageHint || '',
    user: { name: 'Eve', avatarUrl: 'https://picsum.photos/seed/user4/40/40' },
  },
  {
    id: '5',
    name: 'Sony WH-1000XM4 Headphones',
    status: 'Lost',
    category: 'Electronics',
    description: 'Left my black Sony headphones in a study room in the library. They are in a hard-shell case.',
    date: '2024-07-22T12:00:00.000Z',
    location: 'Library',
    imageUrl: placeholderImages.find(img => img.id === 'lost-headphones')?.imageUrl || '',
    imageHint: placeholderImages.find(img => img.id === 'lost-headphones')?.imageHint || '',
    user: { name: 'Frank', avatarUrl: 'https://picsum.photos/seed/user5/40/40' },
  },
  {
    id: '6',
    name: 'Black Hoodie',
    status: 'Found',
    category: 'Clothing',
    description: 'A plain black zip-up hoodie, size medium, was left on a chair in the cafeteria.',
    date: '2024-07-21T16:45:00.000Z',
    location: 'Cafeteria',
    imageUrl: placeholderImages.find(img => img.id === 'found-hoodie')?.imageUrl || '',
    imageHint: placeholderImages.find(img => img.id === 'found-hoodie')?.imageHint || '',
    user: { name: 'Grace', avatarUrl: 'https://picsum.photos/seed/user6/40/40' },
  },
  {
    id: '7',
    name: 'Silver Water Bottle',
    status: 'Resolved',
    category: 'Accessories',
    description: 'Found a silver Hydro Flask water bottle covered in various stickers. It\'s now with its owner.',
    date: '2024-07-18T10:20:00.000Z',
    location: 'Sports Complex',
    imageUrl: placeholderImages.find(img => img.id === 'resolved-bottle')?.imageUrl || '',
    imageHint: placeholderImages.find(img => img.id === 'resolved-bottle')?.imageHint || '',
    user: { name: 'Heidi', avatarUrl: 'https://picsum.photos/seed/user7/40/40' },
  },
  {
    id: '8',
    name: 'AirPods Pro Case',
    status: 'Lost',
    category: 'Electronics',
    description: 'Lost my AirPods Pro charging case (no AirPods inside). It has a green silicone cover on it.',
    date: '2024-07-20T17:00:00.000Z',
    location: 'Hostel',
    imageUrl: placeholderImages.find(img => img.id === 'lost-airpods-case')?.imageUrl || '',
    imageHint: placeholderImages.find(img => img.id === 'lost-airpods-case')?.imageHint || '',
    user: { name: 'Ivan', avatarUrl: 'https://picsum.photos/seed/user8/40/40' },
  },
];
